dist: xenial
language: python
python: 3.7
install:
  - pip install bandit codecov mypy pycodestyle safety typing
  - python setup.py install
script:
  - pip freeze
  - pycodestyle --first --exclude venv,.eggs
  - safety check
  - bandit -r confluence
  - mypy --py2 . --ignore-missing-imports
  - wget https://packages.atlassian.com/list/atlassian-sdk-deb/deb-archive/atlassian-plugin-sdk_6.3.10_all.deb
  - sudo dpkg -i atlassian-plugin-sdk_6.3.10_all.deb
  - yes n | atlas-run-standalone --product confluence --version 6.6.0 --server localhost &>/dev/null &
  - CONFLUENCE_PID=$!
  - >
    until $(curl --fail http://localhost:1990/confluence); do
      sleep 5
    done
  - curl --fail http://localhost:1990/confluence/rest/api/space
  - python setup.py test --addopts "tests integration_tests --cov confluence"
  - kill -9 $CONFLUENCE_PID
after_success:
  - codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: davetcode
  password:
    secure: XgEbiQwqG5x5nhypM8/FPbZR3SIGhwJHzY5wZ5v+ThGpWdJbGl1ntiZy/gwQyUVbLV0AAZFp2hm741JbstO6UH2nD2EObtOK6N/DLwRbf/JBiilnpWbzVtOXZrPuMOeary/M71jFc3EI0f+vO1lxEe0NURjePbj8L2h8HOzc8J8yzZp3XcbvBjPekIfu4bN6qUGl/JQhpAmIjEioea4oWf1PuRgSGcuCtttPaU4ihm9f7y0+L1RQWfOtT+iLc9PzRAK61JGlzU7Om0dWbkGw7YABBQ7FxNWFAmHRdNmDoP0K6Q2iMWyCdUuDdmlEupwCY21iGYSNrDPQ9e/JAJ4+EdphwgQpTVEMh7tTTbh58KhxvL4K0o+I9mZjF3IYNUTwyX1B1To51BSFn+ueTg8bgooxOk5uBEMe4axuMMgHYs1ZQ7fJ3F3fuHm++GP+nAaZTwjt6ICrWU1mTgg2wN91cX3JaP2YjGI3NPQH02BhTiHjZ8VL5erjIX7gKyQvrfzIL+3DPuJlxf67GRXETRvxC3dGTR6i7D2YlhNIaxSqX+Bf6oRERaeRouQy+xuhO5HoEH3cGAwAuEKayhCIM0frWKtg6u3mwXj9eclFG66QtQnj3pRIxd6zC2F+w6GVOYAmazs+ZqO5u+53x7bsTcO3aHv/wNVcmdu0J2H1QAvE/x8=
  on:
    tags: true
    repo: DaveTCode/confluence-python-lib
    condition: "$TRAVIS_TAG =~ ^[0-9]+[.][0-9]+[.][0-9]+(rc[0-9]+|[.]dev[0-9]+)?$"
